# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  project: 'src/NegativeEddy.Leaflet/NegativeEddy.Leaflet.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  Major: '0'
  Minor: '1'
  Patch: '0'

steps:

# do this before all your .NET Core tasks
- task: DotNetCoreInstaller@0
  inputs:
    version: '6.0.100-rc.2.21505.57' # replace this value with the version that you need for your project

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '$(project)'
    arguments: '--configuration $(BuildConfiguration)'

- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    packagesToPush: 'src/NegativeEddy.Leaflet/bin/Release/*.nupkg'
    publishVstsFeed: 'Leaflet'
    allowPackageConflicts: true
    nuGetFeedType: internal
