# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

# do this before all your .NET Core tasks
- task: DotNetCoreInstaller@0
  inputs:
    version: '2.2.105' # replace this value with the version that you need for your project

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/NegativeEddy.Leaflet.csproj'
    arguments: '--configuration Release' # Update this to match your need

# do this near the end of your pipeline in most cases
- task: PublishBuildArtifacts@1

- script: dotnet pack /p:PackageVersion=$(version)  # define version variable elsewhere in your pipeline
- task: NuGetCommand@2
  inputs:
    command: push
    nuGetFeedType: internal
    publishVstsFeed: 'Leaflet
    versioningScheme: byEnvVar
    versionEnvVar: version
